version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80" 
    volumes:
      - ./public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: php:8.3-fpm
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www
     